# IDE

1) Pycharm

2) Thonny 

3) Jupyter Notebook

и др.

# Пример простого кода на Python:


In [ ]:
spam_amount = 0
# int spam_amount = 0;
print(spam_amount, end='\n')

spam_amount = spam_amount + 4
spam_amount += 4
#spam_amount++
if (spam_amount <= 0 and ...): #(or)
    print("I don't want any spam!")
else:
    song = "Spam " * spam_amount
    print(song)

0
Spam Spam Spam Spam Spam Spam Spam Spam 


Основные отличия от C++/Pascal:

1) Назначение переменных.

2) Вызов функций print.

3) Переназначение переменных 

4) Условные операторы

# Типы данных в Python



In [ ]:
#Integer
x = 123
print(type(x))
print(x)

<class 'int'>
123


In [ ]:
#Floats
pi = 3.1415926535897932384626
print(type(pi))
print(pi)
almost_pi = 355 / 113
print(almost_pi)
almost_pi = round(almost_pi, 4)
print(almost_pi)
x_float = 1.
print(x_float)
print(type(x_float))

<class 'float'>
3.141592653589793
3.1415929203539825
3.1416
1.0
<class 'float'>


In [ ]:
#Booleans
x = True # False
print(x)
print(type(x))
x = (3 < 5)
print(x)
x = (3.05 < 5)
y = not (3.9 < 5)
print('x : ', x, 'y : ', y)

True
<class 'bool'>
True
x :  True y :  False


In [ ]:
#Strings
x = "Hello World!"
print(x)
print(type(x))
print(len(x))
x = "abc" + "fed"
print(x)
x = "abc" * 3
print(x)
print(x[0], x[1], x[2])
x = 'Pluto is a planet'
y = "Pluto is a planet"
print(x == y)
print(x[:5], x[-6:]) # :x - первые x символов 
                     # -y: - последние y символов


Hello World!
<class 'str'>
12
abcfed
abcabcabc
a b c
True
Pluto planet


Типы данных аналогичны тем, что есть в С++

# Функции и процедуры в Python


In [ ]:
def least_difference(a, b, c):
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7), 
)

9 0 1


Фрагмент кода создающий функцию least_difference, которая принимает три аргумента, a, b и c.

Функции начинаются с заголовка, представленного ключевым словом def. Блок кода с отступом, следующий за :, выполняется при вызове функции.

return - это еще одно ключевое слово, уникально связанное с функциями. Когда Python встречает оператор return, он немедленно выходит из функции и передает значение в правой части контексту вызова.

# Списки в Python

 Чтобы создать список, необходимо использовать квадратные скобки ([, ]) и разделять каждый элемент запятой. Каждый элемент списка является строкой Python, поэтому каждый элемент заключен в кавычки

In [ ]:
nums = [139, 128, 172, 139, 191, 168, 170]
print(type(nums))
print(nums)

print("Первый элемент:", nums[0])
print("Второй элемент:", nums[1])

print("Последний элемент:", nums[len(nums) - 1])

print("Первые три элемента:", nums[:3])
print("Последние два элемента:", nums[-2:])

<class 'list'>
[139, 128, 172, 139, 191, 168, 170]
Первый элемент: 139
Второй элемент: 128
Последний элемент: 170
Первые три элемента: [139, 128, 172]
Последние два элемента: [168, 170]


**Добавление и удаление элементов**


In [ ]:
nums = [139, 128, 172, 139, 191, 168, 170]

nums.append(1) # добавление в конец списка
nums.insert(0, 2) # вставка на i-ый элемент значение x

nums.remove(128) # удаление первый элемент в списке, имеющий значение x
nums.pop(3) #удаление i-ый элемент

print(nums)

[2, 139, 172, 191, 168, 170, 1]


# Циклы в Python


In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
for planet in planets: # in c++ : for (auto planet : planets)
    print(planet, end=' ')

**В цикле for указывается**:

имя переменной для использования (в данном случае, planet).

набор значений для цикла (в данном случае, planets).

мы используем слово "in", чтобы связать их вместе.

**функция range()**

range() это функция, которая возвращает последовательность чисел. 

Синтаксис: range(start, stop, step)

Параметры:

start: число, начиная с которого должна быть возвращена 
последовательность целых чисел.

stop: число, до которого должна быть возвращена последовательность целых чисел. Диапазон целых чисел заканчивается на stop - 1.

step: целочисленное значение, определяющее шаг между каждым целым числом в последовательности.

In [ ]:
for i in range(-10, 10, 2):
    print("Doing important work. i =", i)

цикл **while**

In [ ]:
i = 0
while i < 10:
    print(i, end=' ')
    i += 1

**Работа со списками**

In [ ]:
squares = [n**2 for n in range(10)]
print(squares)

То же самое с использованием For

In [ ]:
squares = []
for n in range(10):
    squares.append(n**2)
print(squares)

также можно использовать ```if```

In [ ]:
squares_2 = [n**2 for n in range(10) if (n**2 < 50)]
print(squares_2)

Простая задача:

Дан массив. Нужно вывести количество отрицательных чисел в нем.

count_negatives([5, -1, -2, 0, 3])

2

In [ ]:
# 1 решение

def count_negatives(nums):
    n_negative = 0
    for num in nums:
        if num < 0:
            n_negative = n_negative + 1
    return n_negative

In [ ]:
# 2 решение

def count_negatives(nums):
    return len([num for num in nums if num < 0])

# Imports

Некоторые из этих библиотек входят в "стандартную библиотеку". Другие библиотеки можно легко добавить с помощью команды ```import```

**библиотека math**

In [ ]:
import math
print(dir(math))
help(math)

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']
Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (me

In [ ]:
import math as mt
print(mt.pi, mt.log(32, 2))
print(mt.sin(mt.pi/6))

3.141592653589793 5.0
0.49999999999999994


**библиотека numpy**

Главной особенностью numpy является объект array. Массивы схожи со списками в python, исключая тот факт, что элементы массива должны иметь одинаковый тип данных, как float, int и boolean. С массивами можно проводить числовые операции с большим объемом информации в разы быстрее и, главное, намного эффективнее чем со списками.

In [ ]:
import numpy as np

# cоздание массива

a = np.array([1, 2, 3, 4, 10], int)
print(type(a))
print(a)

# манипуляции с массивами

print(a[:2])
print(a[-3:])
a[1] = 14
print(a[1])
print(sum(a))

x = np.array([[1, 2, 3], [6, 5, 4]], float)
print(x)
print(x.shape)
print(len(x))

<class 'numpy.ndarray'>
[ 1  2  3  4 10]
[1 2]
[ 3  4 10]
14
32
[[1. 2. 3.]
 [6. 5. 4.]]
(2, 3)
2


In [ ]:
import numpy as np

xlist = [[1,2,3],[2,4,6],] # создание списка
x = np.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))
print(x[1, 1])

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]
4


In [ ]:
import numpy as np

n = 3
a = np.random.rand(n*n).reshape(n, n)
a = np.random.rand(n, n)
a.fill(19)
print(a, end="\n\n")
a = a.flatten()
print(a, end="\n\n")

[[19. 19. 19.]
 [19. 19. 19.]
 [19. 19. 19.]]

[19. 19. 19. 19. 19. 19. 19. 19. 19.]



**Объеденение одномерных массивов**

In [ ]:
import numpy as np

a = np.array([1, 2, 3], int)
b = np.array([4, 5], int)
c = np.array([6, 7, 8, 9, 10], int)

x = np.concatenate((a, b, c))
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


**Объеденение не одномерных массивов**

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]], int)
print(a, end='\n\n')
b = np.array([[5, 6], [7, 8]], int)
print(b, end='\n\n')

c = np.concatenate((a, b))
print(c, end="\n\n")

c = np.concatenate((a, b), axis = 0)
print(c, end="\n\n")

c = np.concatenate((a, b), axis = 1)
print(c, end="\n\n")

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]



**Другие пути создания массивов**

In [ ]:
import numpy as np

a = np.zeros((2, 3), dtype=int)
print(a, end="\n\n")

b = np.ones((7), dtype=float)
print(b, end="\n\n")

print (np.zeros_like(b), end="\n\n")
print (np.ones_like(a), end="\n\n")

c = np.identity(4, dtype=int)
print(c, end="\n\n")
d = np.eye(4, k=-2, dtype=float)
print(d, end="\n\n")

[[0 0 0]
 [0 0 0]]

[1. 1. 1. 1. 1. 1. 1.]

[0. 0. 0. 0. 0. 0. 0.]

[[1 1 1]
 [1 1 1]]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]



**Операции с массивами**

In [ ]:
import numpy as np

rolls = np.random.randint(low=1, high=6, size=10)
print(rolls)

RollsList = rolls.tolist()
print(RollsList, end="\n\n")

a = np.array([1, 2, 3, 4], int)
b = np.array([5.4, 6.5, 7.987, 8.123], float)

print(np.floor(b))
print(np.ceil(b))
print(np.rint(b), end="\n\n")

print("a+b={}".format(a + b))
print("a-b={}".format(a - b))
print("a*b={}".format(a * b))
print("a/b={}".format(a / b))
print("a%b={}".format(a % b))
print("a**b={}".format(a ** b))
print("sqrt(a)={}\nsqrt(b)={}".format(np.sqrt(a), np.sqrt(b)), end="\n\n")

a = np.array([[0, 1], [2, 3]], float)
b = np.array([[4, 5], [6, 7]], float)
print(a * b)

[4 5 2 3 1 5 2 5 1 1]
[4, 5, 2, 3, 1, 5, 2, 5, 1, 1]

[5. 6. 7. 8.]
[6. 7. 8. 9.]
[5. 6. 8. 8.]

a+b=[ 6.4    8.5   10.987 12.123]
a-b=[-4.4   -4.5   -4.987 -4.123]
a*b=[ 5.4   13.    23.961 32.492]
a/b=[0.18518519 0.30769231 0.37561037 0.49242891]
a%b=[1. 2. 3. 4.]
a**b=[1.00000000e+00 9.05096680e+01 6.46796203e+03 7.77200926e+04]
sqrt(a)=[1.         1.41421356 1.73205081 2.        ]
sqrt(b)=[2.32379001 2.54950976 2.82612809 2.85008772]

[[ 0.  5.]
 [12. 21.]]


При несоответствии в размере компилятор выдает ошибки

In [ ]:
import numpy as np 
a = np.array([1, 2, 3, 4], int)
b = np.array([5, 6, 7, 8, 9], int)
print("a+b={}".format(a + b))

ValueError: ignored

Однако, если размерность массивов не совпадает, они будут преобразованы для выполнения математических операций. 

In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]], int)
b = np.array([7, 8], int)
# 7 8
# 7 8
# 7 8
print(a * b)

[[ 7 16]
 [21 32]
 [35 48]]


In [ ]:
import numpy as np
a = np.array([2, 1, 5, 3, 4], int)

print(np.sum(a))
print(np.prod(a))
print(np.var(a)) # среднее арифметическое
print(np.min(a))
print(np.max(a), end="\n\n")
#индексы минимального и максимального элемента
print(np.argmax(a))
print(np.argmin(a), end="\n\n")


b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], float)
# 1 2 3
# 4 5 6
# 7 8 9
print(np.sum(b, axis=0))
print(np.max(b, axis=1), end="\n\n")

a = np.sort(a)
print(a)

a = a.clip(2, 4) # min(max(a[i], minval), maxval)
print(a)

15
120
2.0
1
5

2
1

[12. 15. 18.]
[3. 6. 9.]

[1 2 3 4 5]
[2 2 3 4 4]


**Операторы сравнения**

In [ ]:
import numpy as np

a = np.random.randint(low=1, high=6, size=10)
print(a)

b = np.random.randint(low=-6, high=-1, size=10)

b = b + 10
print(b)

print(a <= b)
print(a == b, end="\n\n")

print(any(a == b))
print(all(a > b), end="\n\n")


a = np.array([1, 3, 0], float)
print(np.logical_and(a > 0, a < 3))

b = np.array([True, False, False], bool)
print(np.logical_not(b))

c = np.array([False, True, False], bool)
print(np.logical_or(b, c))

d = np.array([1, -3, 0], float)
print(np.where(d > 0, 1, -1))


e = np.array([[0, 1], [-3, 0]], float)
print(np.nonzero(e))


f = np.array([1, np.NaN, np.Inf], float)
print(f)
print(np.isnan(f))
print(np.isfinite(f))

[5 4 2 3 1 2 2 1 4 3]
[7 4 5 6 4 7 4 8 5 8]
[ True  True  True  True  True  True  True  True  True  True]
[False  True False False False False False False False False]

True
False

[ True False False]
[False  True  True]
[ True  True False]
[ 1 -1 -1]
(array([0, 1]), array([1, 0]))
[ 1. nan inf]
[False  True False]
[ True False False]


**Выбор элементов массива и манипуляция с ними**

In [ ]:
import numpy as np

a = np.array([[6, 4], [5, 9]], float)
print(a >= 6)
print(a[a >= 6])
print(a[np.logical_and(a > 4, a < 7)], end="\n\n")

#
c = np.array([0, 2, 4, 3, 1], int)
d = np.array([1, 2, 3, 4, 5], int)
print(d[c]) 
print(d[[0, 2, 4, 3, 1]], end="\n\n")

#
e = np.array([[1, 4], [9, 16]], float)
f = np.array([0, 0, 1, 1, 0], int)
g = np.array([0, 1, 1, 1, 1], int)
print(e[f, g], end="\n\n")
#
h = np.array([0, 1, 2, 3, 4, 5], float)
i = np.array([9, 8, 7], int)
h.put([0, 3], i)
print(h)
h.put([0, 3], 5)
print(h)

[[ True False]
 [False  True]]
[6. 9.]
[6. 5.]

[1 3 5 4 2]
[1 3 5 4 2]

[ 1.  4. 16. 16.  4.]

[9. 1. 2. 8. 4. 5.]
[5. 1. 2. 5. 4. 5.]


**Векторная и матричная математика**

In [ ]:
import numpy as np

a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)

print(np.dot(b, a))
print(np.dot(a, b), end="\n\n")

print(np.dot(a, c))
print(np.dot(c, a), end="\n\n")

print(np.dot(b, c))
print(np.dot(c, b))

[ 6. 11.]
[ 3. 13.]

[[ 4.  0.]
 [14.  2.]]
[[2. 4.]
 [0. 4.]]

[14.  2.]
[5. 8.]


Также можно получить скалярное произведение.

In [ ]:
import numpy as np

a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)

print(np.outer(a, b)) # скалярное произведение

[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]


**Математика многочленов**


In [ ]:
import numpy as np

print(np.poly([-1, 1, 1, 10])) # из списка корней получаем коэффициенты уравнения
#x^4 - 11x^3 + 9x^2 + 11x - 10 = 0
print(np.roots([1, 4, -2, 3])) # из списка коэффициентов получаем корни уравнения
print(np.polyder([1./4., 1./3., 1./2., 1., 0.]), end="\n\n") # производная функции

a = np.array([1, 3, -4, -2], int)
b = np.array([-2, 5, 2, -7], int)
#сложение, вычитание, умножение и деление многочленов
print(np.polyadd(a, b))
print(np.polysub(a, b))
print(np.polymul(a, b))
print(np.polydiv(a, b), end="\n\n")


[  1. -11.   9.  11. -10.]
[-4.5797401 +0.j          0.28987005+0.75566815j  0.28987005-0.75566815j]
[1. 1. 1. 1.]

[-1  8 -2 -9]
[ 3 -2 -6  5]
[ -2  -1  25 -17 -39  24  14]
(array([-0.5]), array([ 5.5, -3. , -5.5]))



# Д/з
**1)** Найти максимальный элемент в массиве, перед которыми стоит элемент равный 0.

Входные данные:

7

6 3 0 5 0 0 2

Ответ:

5


**2)** Даны два массива. Необходимо узнать, равны они или нет.

Входные данные:

4

1 2 3 4

4

3 5 1 2

Ответ:

False

Входные данные:

4

1 2 3 4

4

2 4 1 3

Ответ:

True


**3)** Найти произведение k-й диагонали в двумерной матрице.

Входные данные:

3

1 2 3

4 5 6

7 8 9

1

Ответ:

12


**4)** Даны суммы по всём столбцам и строкам двумерной матрицы. Нужно восстановить изначальную матрицу.

Входные данные:

3

6 15 24

12 15 18

Ответ:

1 2 3

4 5 6

7 8 9

**Примечание**

In [ ]:
# ввод данных
n = int(input()) # ввод одного целого число
t, m = map(float, input().split()) # ввод 2 вещественных чисел
a = list(map(int, input().split())) # ввод списка
b = [list(map(int, input().split())) for i in range(n)] # ввод двумерного списка